name: Test and Evaluate Assignments

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have any additional dependencies

      - name: Initialize README if not exists
        run: |
          if [ ! -f README.md ]; then
            echo -e "# Assignment Scores\n\n## Scores\n\n" > README.md
          fi

      - name: Run pytest and collect results
        run: |
          pytest --junitxml=test-results.xml

      - name: Parse test results and calculate scores
        run: |
          # Example script to parse JUnit XML and calculate scores
          python parse_test_results.py test-results.xml > scores.json

      - name: Publish scores to README.md
        run: |
          python update_readme.py scores.json README.md
        if: success()  # Only publish scores if tests were successful

      - name: Commit changes to repository
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add README.md
          git commit -m "Update scores"
          git push origin HEAD:main
        if: success()  # Commit changes only if previous steps were successful
