name: Sync branches with main

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Fetch all branches
        run: git fetch --all

      - name: List branches
        id: list-branches
        run: |
          echo "::set-output name=branches::$(git branch -r | grep -v '\->' | grep -v 'main' | sed 's/origin\///' | tr '\n' ' ')"

      - name: Sync branches
        run: |
          for branch in ${{ steps.list-branches.outputs.branches }}; do
            echo "Syncing branch $branch with main"
            git checkout $branch
            git merge --ff-only origin/main || git merge --abort
            git push origin $branch
          done
