name: Sync Branches with Main

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Fetch all branches
        run: git fetch --all

      - name: Get branches
        run: echo "BRANCHES=$(git branch -r | grep -v '\->' | grep -v 'main' | sed 's/origin\///' | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Sync branches with main
        run: |
          for branch in ${BRANCHES}; do
            echo "Syncing branch $branch with main"
            git checkout $branch
            git rebase origin/main || git rebase --abort
            git push --force-with-lease origin $branch
          done
